In [1]:
import pandas as pd

In [3]:
multi=pd.read_csv(r"H:\machine learning\New Datasets\DataSets-master\DataSets-master\Advertising.csv")

In [4]:
multi

     Unnamed: 0     TV  radio  newspaper  sales
0             1  230.1   37.8       69.2   22.1
1             2   44.5   39.3       45.1   10.4
2             3   17.2   45.9       69.3    9.3
3             4  151.5   41.3       58.5   18.5
4             5  180.8   10.8       58.4   12.9
5             6    8.7   48.9       75.0    7.2
6             7   57.5   32.8       23.5   11.8
7             8  120.2   19.6       11.6   13.2
8             9    8.6    2.1        1.0    4.8
9            10  199.8    2.6       21.2   10.6
10           11   66.1    5.8       24.2    8.6
11           12  214.7   24.0        4.0   17.4
12           13   23.8   35.1       65.9    9.2
13           14   97.5    7.6        7.2    9.7
14           15  204.1   32.9       46.0   19.0
15           16  195.4   47.7       52.9   22.4
16           17   67.8   36.6      114.0   12.5
17           18  281.4   39.6       55.8   24.4
18           19   69.2   20.5       18.3   11.3
19           20  147.3   23.9       19.1   14.6
20           21  218.4   27.7       53.4   18.0
21           22  237.4    5.1       23.5   12.5
22           23   13.2   15.9       49.6    5.6
23           24  228.3   16.9       26.2   15.5
24           25   62.3   12.6       18.3    9.7
25           26  262.9    3.5       19.5   12.0
26           27  142.9   29.3       12.6   15.0
27           28  240.1   16.7       22.9   15.9
28           29  248.8   27.1       22.9   18.9
29           30   70.6   16.0       40.8   10.5
..          ...    ...    ...        ...    ...
170         171   50.0   11.6       18.4    8.4
171         172  164.5   20.9       47.4   14.5
172         173   19.6   20.1       17.0    7.6
173         174  168.4    7.1       12.8   11.7
174         175  222.4    3.4       13.1   11.5
175         176  276.9   48.9       41.8   27.0
176         177  248.4   30.2       20.3   20.2
177         178  170.2    7.8       35.2   11.7
178         179  276.7    2.3       23.7   11.8
179         180  165.6   10.0       17.6   12.6
180         181  156.6    2.6        8.3   10.5
181         182  218.5    5.4       27.4   12.2
182         183   56.2    5.7       29.7    8.7
183         184  287.6   43.0       71.8   26.2
184         185  253.8   21.3       30.0   17.6
185         186  205.0   45.1       19.6   22.6
186         187  139.5    2.1       26.6   10.3
187         188  191.1   28.7       18.2   17.3
188         189  286.0   13.9        3.7   15.9
189         190   18.7   12.1       23.4    6.7
190         191   39.5   41.1        5.8   10.8
191         192   75.5   10.8        6.0    9.9
192         193   17.2    4.1       31.6    5.9
193         194  166.8   42.0        3.6   19.6
194         195  149.7   35.6        6.0   17.3
195         196   38.2    3.7       13.8    7.6
196         197   94.2    4.9        8.1    9.7
197         198  177.0    9.3        6.4   12.8
198         199  283.6   42.0       66.2   25.5
199         200  232.1    8.6        8.7   13.4

[200 rows x 5 columns]

In [5]:
multi.head(5)

   Unnamed: 0     TV  radio  newspaper  sales
0           1  230.1   37.8       69.2   22.1
1           2   44.5   39.3       45.1   10.4
2           3   17.2   45.9       69.3    9.3
3           4  151.5   41.3       58.5   18.5
4           5  180.8   10.8       58.4   12.9

In [6]:
multi.shape

(200, 5)

In [7]:
x_input=multi.iloc[:,1:4]

In [8]:
x_input.head(5)

      TV  radio  newspaper
0  230.1   37.8       69.2
1   44.5   39.3       45.1
2   17.2   45.9       69.3
3  151.5   41.3       58.5
4  180.8   10.8       58.4

In [21]:
y_output=multi.iloc[:,4]

In [22]:
multi.keys()

Index(['Unnamed: 0', 'TV', 'radio', 'newspaper', 'sales'], dtype='object')

In [23]:
y_output

0      22.1
1      10.4
2       9.3
3      18.5
4      12.9
5       7.2
6      11.8
7      13.2
8       4.8
9      10.6
10      8.6
11     17.4
12      9.2
13      9.7
14     19.0
15     22.4
16     12.5
17     24.4
18     11.3
19     14.6
20     18.0
21     12.5
22      5.6
23     15.5
24      9.7
25     12.0
26     15.0
27     15.9
28     18.9
29     10.5
       ...
170     8.4
171    14.5
172     7.6
173    11.7
174    11.5
175    27.0
176    20.2
177    11.7
178    11.8
179    12.6
180    10.5
181    12.2
182     8.7
183    26.2
184    17.6
185    22.6
186    10.3
187    17.3
188    15.9
189     6.7
190    10.8
191     9.9
192     5.9
193    19.6
194    17.3
195     7.6
196     9.7
197    12.8
198    25.5
199    13.4
Name: sales, Length: 200, dtype: float64

In [64]:
x_input.shape
#y_output.shape

(200, 3)

In [65]:
#or we can use (200,3) to reshape 
X_input=x_input.values.reshape(200,3)

In [66]:
#or we can use (200,1) to reshape
Y_output=y_output.values.reshape(200,1)

In [67]:
Y_output

array([[22.1],
       [10.4],
       [ 9.3],
       [18.5],
       [12.9],
       [ 7.2],
       [11.8],
       [13.2],
       [ 4.8],
       [10.6],
       [ 8.6],
       [17.4],
       [ 9.2],
       [ 9.7],
       [19. ],
       [22.4],
       [12.5],
       [24.4],
       [11.3],
       [14.6],
       [18. ],
       [12.5],
       [ 5.6],
       [15.5],
       [ 9.7],
       [12. ],
       [15. ],
       [15.9],
       [18.9],
       [10.5],
       [21.4],
       [11.9],
       [ 9.6],
       [17.4],
       [ 9.5],
       [12.8],
       [25.4],
       [14.7],
       [10.1],
       [21.5],
       [16.6],
       [17.1],
       [20.7],
       [12.9],
       [ 8.5],
       [14.9],
       [10.6],
       [23.2],
       [14.8],
       [ 9.7],
       [11.4],
       [10.7],
       [22.6],
       [21.2],
       [20.2],
       [23.7],
       [ 5.5],
       [13.2],
       [23.8],
       [18.4],
       [ 8.1],
       [24.2],
       [15.7],
       [14. ],
       [18. ],
       [ 9.3],
       [ 9.5],
       [13.4],
       [18.9],
       [22.3],
       [18.3],
       [12.4],
       [ 8.8],
       [11. ],
       [17. ],
       [ 8.7],
       [ 6.9],
       [14.2],
       [ 5.3],
       [11. ],
       [11.8],
       [12.3],
       [11.3],
       [13.6],
       [21.7],
       [15.2],
       [12. ],
       [16. ],
       [12.9],
       [16.7],
       [11.2],
       [ 7.3],
       [19.4],
       [22.2],
       [11.5],
       [16.9],
       [11.7],
       [15.5],
       [25.4],
       [17.2],
       [11.7],
       [23.8],
       [14.8],
       [14.7],
       [20.7],
       [19.2],
       [ 7.2],
       [ 8.7],
       [ 5.3],
       [19.8],
       [13.4],
       [21.8],
       [14.1],
       [15.9],
       [14.6],
       [12.6],
       [12.2],
       [ 9.4],
       [15.9],
       [ 6.6],
       [15.5],
       [ 7. ],
       [11.6],
       [15.2],
       [19.7],
       [10.6],
       [ 6.6],
       [ 8.8],
       [24.7],
       [ 9.7],
       [ 1.6],
       [12.7],
       [ 5.7],
       [19.6],
       [10.8],
       [11.6],
       [ 9.5],
       [20.8],
       [ 9.6],
       [20.7],
       [10.9],
       [19.2],
       [20.1],
       [10.4],
       [11.4],
       [10.3],
       [13.2],
       [25.4],
       [10.9],
       [10.1],
       [16.1],
       [11.6],
       [16.6],
       [19. ],
       [15.6],
       [ 3.2],
       [15.3],
       [10.1],
       [ 7.3],
       [12.9],
       [14.4],
       [13.3],
       [14.9],
       [18. ],
       [11.9],
       [11.9],
       [ 8. ],
       [12.2],
       [17.1],
       [15. ],
       [ 8.4],
       [14.5],
       [ 7.6],
       [11.7],
       [11.5],
       [27. ],
       [20.2],
       [11.7],
       [11.8],
       [12.6],
       [10.5],
       [12.2],
       [ 8.7],
       [26.2],
       [17.6],
       [22.6],
       [10.3],
       [17.3],
       [15.9],
       [ 6.7],
       [10.8],
       [ 9.9],
       [ 5.9],
       [19.6],
       [17.3],
       [ 7.6],
       [ 9.7],
       [12.8],
       [25.5],
       [13.4]])

In [68]:
X_train=X_input[:140]

In [69]:
X_test=X_input[140:]

In [70]:
Y_train=Y_output[:140]

In [71]:
Y_test=Y_output[140:]

In [72]:
from sklearn.linear_model import LinearRegression

In [73]:
teacher=LinearRegression()

In [74]:
learner=teacher.fit(X_train,Y_train)

In [75]:
yp=learner.predict(X_test)
yplist=list(yp)

In [76]:
ya=Y_test

In [77]:
multi.head(5)

   Unnamed: 0     TV  radio  newspaper  sales
0           1  230.1   37.8       69.2   22.1
1           2   44.5   39.3       45.1   10.4
2           3   17.2   45.9       69.3    9.3
3           4  151.5   41.3       58.5   18.5
4           5  180.8   10.8       58.4   12.9

In [78]:
xlist=list(X_test)
yalist=list(Y_test)

In [94]:
newtable=pd.DataFrame({"ya":yalist,"yp":yplist})

In [95]:
newtable

        ya                    yp
0   [10.9]   [9.514354402169253]
1   [19.2]   [18.29202876551769]
2   [20.1]  [19.270940642386797]
3   [10.4]    [8.88723581838406]
4   [11.4]  [10.113617055260615]
5   [10.3]   [9.960419720902921]
6   [13.2]  [15.627067876574085]
7   [25.4]  [23.158701304668185]
8   [10.9]  [12.038450307585519]
9   [10.1]   [9.722124713181572]
10  [16.1]  [18.638094550760975]
11  [11.6]  [10.100998672157097]
12  [16.6]  [16.485896155663326]
13  [19.0]   [18.12468608681111]
14  [15.6]  [15.643642664262023]
15   [3.2]  [5.3052327502539605]
16  [15.3]  [15.127442314978547]
17  [10.1]  [10.253587248475565]
18   [7.3]  [10.090062519977868]
19  [12.9]  [12.443627914665923]
20  [14.4]   [14.32103089965689]
21  [13.3]  [13.361690795894438]
22  [14.9]  [15.084433307031002]
23  [18.0]  [17.327694332838675]
24  [11.9]   [11.18435748639172]
25  [11.9]   [14.43410809882653]
26   [8.0]  [10.578473771006653]
27  [12.2]  [13.650852981324158]
28  [17.1]  [17.246826043164646]
29  [15.0]  [18.306486232149716]
30   [8.4]   [7.426596522505593]
31  [14.5]  [14.397560883879724]
32   [7.6]   [7.527829822376982]
33  [11.7]   [12.20541804669305]
34  [11.5]  [14.080318082619868]
35  [27.0]   [24.73378746238135]
36  [20.2]  [20.097447817388655]
37  [11.7]  [12.348559104890656]
38  [11.8]  [16.405551172818093]
39  [12.6]  [12.580335695447781]
40  [10.5]  [10.855195206145957]
41  [12.2]  [14.213214623470476]
42   [8.7]   [6.624205822822251]
43  [26.2]   [24.08691175796603]
44  [17.6]  [18.723178110598568]
45  [22.6]  [20.734915499920106]
46  [10.3]    [9.90581942726528]
47  [17.3]   [17.13834560975087]
48  [15.9]  [18.987537878840776]
49   [6.7]   [6.028786481433874]
50  [10.8]  [12.271103667395423]
51   [9.9]   [8.519860500298424]
52   [5.9]    [4.49610391471514]
53  [19.6]  [18.428727669427765]
54  [17.3]  [16.467010742030695]
55   [7.6]   [5.465752076214399]
56   [9.7]    [8.33322951033632]
57  [12.8]  [13.024574894348158]
58  [25.5]  [23.735865210655057]
59  [13.4]  [15.484266315565687]

In [96]:
#error
from sklearn.metrics import mean_squared_error
import numpy as np

In [97]:
error=np.sqrt(mean_squared_error(ya,yp))

In [98]:
error

1.5993642253910214

In [99]:
m= learner.coef_

In [100]:
m

array([[ 0.04704868,  0.17968299, -0.00300557]])

In [101]:
c=learner.intercept_

In [102]:
c

array([3.04514221])

In [103]:
m1=m[0,0]

In [104]:
m1

0.047048680822289274

In [105]:
m3=m[0,2]

In [106]:
m3

-0.003005565156806662