In [1]:
import numpy as np
import pandas as pd

In [2]:
bmi=pd.read_csv(r"H:\machine learning\New Datasets\DataSets-master\DataSets-master\bmi.csv")

In [3]:
bmi

     Gender  Height  Weight  Index
0      Male     174      96      4
1      Male     189      87      2
2    Female     185     110      4
3    Female     195     104      3
4      Male     149      61      3
5      Male     189     104      3
6      Male     147      92      5
7      Male     154     111      5
8      Male     174      90      3
9    Female     169     103      4
10     Male     195      81      2
11   Female     159      80      4
12   Female     192     101      3
13     Male     155      51      2
14     Male     191      79      2
15   Female     153     107      5
16   Female     157     110      5
17     Male     140     129      5
18     Male     144     145      5
19     Male     172     139      5
20     Male     157     110      5
21   Female     153     149      5
22   Female     169      97      4
23     Male     185     139      5
24   Female     172      67      2
25   Female     151      64      3
26     Male     190      95      3
27     Male     187      62      1
28   Female     163     159      5
29     Male     179     152      5
..      ...     ...     ...    ...
470    Male     147     142      5
471    Male     154     112      5
472  Female     178      65      2
473    Male     195     153      5
474  Female     167      79      3
475    Male     183     131      4
476  Female     164     142      5
477    Male     167      64      2
478  Female     151      55      2
479  Female     147     107      5
480  Female     155     115      5
481  Female     172     108      4
482  Female     142      86      5
483    Male     146      85      4
484  Female     188     115      4
485    Male     173     111      4
486  Female     160     109      5
487    Male     187      80      2
488    Male     198     136      4
489  Female     179     150      5
490  Female     164      59      2
491  Female     146     147      5
492  Female     198      50      0
493  Female     170      53      1
494    Male     152      98      5
495  Female     150     153      5
496  Female     184     121      4
497  Female     141     136      5
498    Male     150      95      5
499    Male     173     131      5

[500 rows x 4 columns]

In [4]:
bmi.Gender[bmi.Gender=="Male"]=1

C:\Users\Rahul\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [5]:
bmi.Gender[bmi.Gender=="Female"]=0

C:\Users\Rahul\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [6]:
bmi

    Gender  Height  Weight  Index
0        1     174      96      4
1        1     189      87      2
2        0     185     110      4
3        0     195     104      3
4        1     149      61      3
5        1     189     104      3
6        1     147      92      5
7        1     154     111      5
8        1     174      90      3
9        0     169     103      4
10       1     195      81      2
11       0     159      80      4
12       0     192     101      3
13       1     155      51      2
14       1     191      79      2
15       0     153     107      5
16       0     157     110      5
17       1     140     129      5
18       1     144     145      5
19       1     172     139      5
20       1     157     110      5
21       0     153     149      5
22       0     169      97      4
23       1     185     139      5
24       0     172      67      2
25       0     151      64      3
26       1     190      95      3
27       1     187      62      1
28       0     163     159      5
29       1     179     152      5
..     ...     ...     ...    ...
470      1     147     142      5
471      1     154     112      5
472      0     178      65      2
473      1     195     153      5
474      0     167      79      3
475      1     183     131      4
476      0     164     142      5
477      1     167      64      2
478      0     151      55      2
479      0     147     107      5
480      0     155     115      5
481      0     172     108      4
482      0     142      86      5
483      1     146      85      4
484      0     188     115      4
485      1     173     111      4
486      0     160     109      5
487      1     187      80      2
488      1     198     136      4
489      0     179     150      5
490      0     164      59      2
491      0     146     147      5
492      0     198      50      0
493      0     170      53      1
494      1     152      98      5
495      0     150     153      5
496      0     184     121      4
497      0     141     136      5
498      1     150      95      5
499      1     173     131      5

[500 rows x 4 columns]

In [7]:
feature=bmi.iloc[:,0:3]

In [8]:
feature

    Gender  Height  Weight
0        1     174      96
1        1     189      87
2        0     185     110
3        0     195     104
4        1     149      61
5        1     189     104
6        1     147      92
7        1     154     111
8        1     174      90
9        0     169     103
10       1     195      81
11       0     159      80
12       0     192     101
13       1     155      51
14       1     191      79
15       0     153     107
16       0     157     110
17       1     140     129
18       1     144     145
19       1     172     139
20       1     157     110
21       0     153     149
22       0     169      97
23       1     185     139
24       0     172      67
25       0     151      64
26       1     190      95
27       1     187      62
28       0     163     159
29       1     179     152
..     ...     ...     ...
470      1     147     142
471      1     154     112
472      0     178      65
473      1     195     153
474      0     167      79
475      1     183     131
476      0     164     142
477      1     167      64
478      0     151      55
479      0     147     107
480      0     155     115
481      0     172     108
482      0     142      86
483      1     146      85
484      0     188     115
485      1     173     111
486      0     160     109
487      1     187      80
488      1     198     136
489      0     179     150
490      0     164      59
491      0     146     147
492      0     198      50
493      0     170      53
494      1     152      98
495      0     150     153
496      0     184     121
497      0     141     136
498      1     150      95
499      1     173     131

[500 rows x 3 columns]

In [9]:
target=bmi.iloc[:,3:4]

In [10]:
target

     Index
0        4
1        2
2        4
3        3
4        3
5        3
6        5
7        5
8        3
9        4
10       2
11       4
12       3
13       2
14       2
15       5
16       5
17       5
18       5
19       5
20       5
21       5
22       4
23       5
24       2
25       3
26       3
27       1
28       5
29       5
..     ...
470      5
471      5
472      2
473      5
474      3
475      4
476      5
477      2
478      2
479      5
480      5
481      4
482      5
483      4
484      4
485      4
486      5
487      2
488      4
489      5
490      2
491      5
492      0
493      1
494      5
495      5
496      4
497      5
498      5
499      5

[500 rows x 1 columns]

In [11]:
feature=feature.values.reshape(len(feature),3)
target=target.values.reshape(len(target),1)

In [12]:
feature

array([[1, 174, 96],
       [1, 189, 87],
       [0, 185, 110],
       ...,
       [0, 141, 136],
       [1, 150, 95],
       [1, 173, 131]], dtype=object)

In [13]:
target

array([[4],
       [2],
       [4],
       [3],
       [3],
       [3],
       [5],
       [5],
       [3],
       [4],
       [2],
       [4],
       [3],
       [2],
       [2],
       [5],
       [5],
       [5],
       [5],
       [5],
       [5],
       [5],
       [4],
       [5],
       [2],
       [3],
       [3],
       [1],
       [5],
       [5],
       [5],
       [1],
       [1],
       [5],
       [5],
       [4],
       [3],
       [4],
       [5],
       [2],
       [4],
       [5],
       [2],
       [5],
       [4],
       [2],
       [4],
       [4],
       [3],
       [5],
       [5],
       [1],
       [5],
       [4],
       [4],
       [3],
       [4],
       [5],
       [3],
       [5],
       [0],
       [5],
       [0],
       [2],
       [5],
       [5],
       [4],
       [2],
       [4],
       [4],
       [2],
       [4],
       [5],
       [2],
       [3],
       [4],
       [4],
       [4],
       [4],
       [0],
       [3],
       [5],
       [3],
       [4],
       [5],
       [0],
       [5],
       [5],
       [5],
       [5],
       [5],
       [3],
       [3],
       [2],
       [4],
       [5],
       [4],
       [5],
       [1],
       [0],
       [4],
       [5],
       [5],
       [4],
       [4],
       [4],
       [5],
       [5],
       [4],
       [3],
       [4],
       [5],
       [4],
       [2],
       [4],
       [3],
       [2],
       [5],
       [5],
       [5],
       [4],
       [4],
       [4],
       [5],
       [5],
       [4],
       [4],
       [4],
       [5],
       [2],
       [5],
       [2],
       [5],
       [4],
       [5],
       [5],
       [5],
       [3],
       [5],
       [5],
       [2],
       [4],
       [5],
       [5],
       [5],
       [4],
       [3],
       [5],
       [3],
       [3],
       [0],
       [3],
       [3],
       [5],
       [5],
       [4],
       [3],
       [5],
       [3],
       [4],
       [2],
       [2],
       [3],
       [5],
       [4],
       [2],
       [4],
       [5],
       [3],
       [2],
       [4],
       [5],
       [5],
       [4],
       [4],
       [4],
       [4],
       [3],
       [5],
       [3],
       [3],
       [4],
       [4],
       [2],
       [3],
       [3],
       [5],
       [3],
       [5],
       [4],
       [5],
       [5],
       [4],
       [5],
       [5],
       [5],
       [4],
       [4],
       [5],
       [5],
       [1],
       [3],
       [4],
       [4],
       [5],
       [4],
       [5],
       [4],
       [3],
       [4],
       [4],
       [5],
       [5],
       [5],
       [0],
       [5],
       [5],
       [5],
       [5],
       [5],
       [2],
       [5],
       [4],
       [5],
       [0],
       [5],
       [3],
       [4],
       [5],
       [5],
       [4],
       [2],
       [3],
       [3],
       [4],
       [3],
       [5],
       [5],
       [2],
       [5],
       [3],
       [2],
       [1],
       [5],
       [0],
       [5],
       [3],
       [5],
       [3],
       [4],
       [3],
       [5],
       [5],
       [5],
       [5],
       [2],
       [4],
       [5],
       [5],
       [4],
       [5],
       [5],
       [5],
       [2],
       [4],
       [5],
       [5],
       [5],
       [5],
       [1],
       [5],
       [5],
       [4],
       [0],
       [3],
       [3],
       [4],
       [2],
       [3],
       [1],
       [1],
       [5],
       [5],
       [4],
       [4],
       [4],
       [4],
       [5],
       [2],
       [5],
       [4],
       [3],
       [3],
       [4],
       [5],
       [5],
       [2],
       [4],
       [3],
       [4],
       [5],
       [4],
       [2],
       [4],
       [5],
       [4],
       [5],
       [5],
       [1],
       [5],
       [5],
       [5],
       [5],
       [2],
       [2],
       [5],
       [3],
       [5],
       [4],
       [5],
       [4],
       [4],
       [5],
       [5],
       [4],
       [2],
       [2],
       [4],
       [3],
       [3],
       [5],
       [4],
       [2],
       [2],
       [2],
       [2],
       [5],
       [5],
       [4],
       [5],
       [3],
       [4],
       [4],
       [3],
       [4],
       [4],
       [2],
       [2],
       [5],
       [2],
       [2],
       [2],
       [2],
       [5],
       [0],
       [3],
       [4],
       [5],
       [1],
       [4],
       [1],
       [4],
       [5],
       [4],
       [5],
       [5],
       [3],
       [4],
       [5],
       [4],
       [3],
       [5],
       [1],
       [2],
       [4],
       [5],
       [5],
       [5],
       [5],
       [3],
       [5],
       [1],
       [4],
       [5],
       [5],
       [2],
       [5],
       [4],
       [3],
       [2],
       [2],
       [2],
       [2],
       [3],
       [5],
       [3],
       [3],
       [5],
       [3],
       [5],
       [3],
       [4],
       [2],
       [4],
       [4],
       [5],
       [2],
       [5],
       [5],
       [5],
       [1],
       [4],
       [5],
       [5],
       [5],
       [4],
       [5],
       [2],
       [5],
       [2],
       [1],
       [5],
       [5],
       [4],
       [1],
       [1],
       [4],
       [4],
       [4],
       [4],
       [2],
       [5],
       [5],
       [4],
       [2],
       [5],
       [5],
       [5],
       [1],
       [5],
       [4],
       [2],
       [5],
       [5],
       [4],
       [5],
       [4],
       [4],
       [5],
       [5],
       [5],
       [4],
       [5],
       [0],
       [2],
       [2],
       [4],
       [2],
       [4],
       [5],
       [4],
       [5],
       [1],
       [5],
       [2],
       [5],
       [3],
       [5],
       [5],
       [3],
       [5],
       [5],
       [2],
       [5],
       [3],
       [4],
       [5],
       [2],
       [2],
       [5],
       [5],
       [4],
       [5],
       [4],
       [4],
       [4],
       [5],
       [2],
       [4],
       [5],
       [2],
       [5],
       [0],
       [1],
       [5],
       [5],
       [4],
       [5],
       [5],
       [5]], dtype=int64)

In [14]:
from sklearn.naive_bayes import GaussianNB,BernoulliNB,MultinomialNB
from sklearn.neighbors import KNeighborsClassifier

In [15]:
featureTrain=feature[:370]
featureTest=feature[370:]
targetTrain=target[:370]
targetTest=target[370:]

In [16]:
teacherGaussian=GaussianNB()
teacherBernouli=BernoulliNB()
teacherMultinomial=MultinomialNB()
teacherKnn=KNeighborsClassifier()

In [17]:
learnerGaussian=teacherGaussian.fit(featureTrain,targetTrain)
learnerBernouli=teacherBernouli.fit(featureTrain,targetTrain)
learnerMultinomial=teacherMultinomial.fit(featureTrain,targetTrain)
learnerKnn=teacherKnn.fit(featureTrain,targetTrain)

C:\Users\Rahul\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\utils\validation.py:578: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Rahul\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:4: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  after removing the cwd from sys.path.

In [18]:
index=pd.Series(["Extremely weak","Weak","Normal","Overweight","Obesity","Extreme Obesity"])

In [19]:
index[2]

'Normal'

In [20]:
result=learnerKnn.predict([[1,170,65]])
index[result]

2    Normal
dtype: object

In [21]:
result=learnerGaussian.predict([[1,170,65]])
index[result]

2    Normal
dtype: object

In [22]:
result=learnerBernouli.predict([[1,170,65]])
index[result]

5    Extreme Obesity
dtype: object

In [23]:
result=learnerMultinomial.predict([[1,170,65]])
index[result]

2    Normal
dtype: object

In [24]:
Ya=targetTest
Yp=learnerGaussian.predict(featureTest)

In [25]:
Yalist=list(Ya)
Yplist=list(Yp)

In [26]:
table=pd.DataFrame({"Ya":Yalist,"Yp":Yplist})

In [27]:
table

      Ya  Yp
0    [3]   2
1    [5]   5
2    [1]   1
3    [2]   2
4    [4]   4
5    [5]   5
6    [5]   5
7    [5]   5
8    [5]   4
9    [3]   3
10   [5]   5
11   [1]   1
12   [4]   4
13   [5]   5
14   [5]   5
15   [2]   2
16   [5]   5
17   [4]   3
18   [3]   2
19   [2]   2
20   [2]   2
21   [2]   2
22   [2]   2
23   [3]   3
24   [5]   5
25   [3]   2
26   [3]   3
27   [5]   5
28   [3]   2
29   [5]   5
..   ...  ..
100  [5]   5
101  [5]   5
102  [2]   2
103  [5]   5
104  [3]   2
105  [4]   5
106  [5]   5
107  [2]   2
108  [2]   2
109  [5]   5
110  [5]   5
111  [4]   4
112  [5]   4
113  [4]   4
114  [4]   4
115  [4]   4
116  [5]   5
117  [2]   3
118  [4]   4
119  [5]   5
120  [2]   2
121  [5]   5
122  [0]   0
123  [1]   2
124  [5]   5
125  [5]   5
126  [4]   4
127  [5]   5
128  [5]   4
129  [5]   5

[130 rows x 2 columns]

In [28]:
table.head(5)

    Ya  Yp
0  [3]   2
1  [5]   5
2  [1]   1
3  [2]   2
4  [4]   4

In [29]:
from sklearn.metrics import accuracy_score

In [30]:
acc=accuracy_score(Ya,Yp)*100

In [31]:
acc

75.38461538461539

In [32]:
Ya=targetTest
Yp=learnerKnn.predict(featureTest)

In [33]:
Yalist=list(Ya)
Yplist=list(Yp)

In [34]:
table=pd.DataFrame({"Actual Value":Yalist,"Predicted value":Yplist})

In [35]:
acc=accuracy_score(Ya,Yp)*100

In [36]:
acc

92.3076923076923