#### import pandas as pd
import numpy as np

In [22]:
databmi=pd.read_csv(r"H:\machine learning\New Datasets\DataSets-master\DataSets-master\bmi.csv")

In [23]:
databmi

     Gender  Height  Weight  Index
0      Male     174      96      4
1      Male     189      87      2
2    Female     185     110      4
3    Female     195     104      3
4      Male     149      61      3
5      Male     189     104      3
6      Male     147      92      5
7      Male     154     111      5
8      Male     174      90      3
9    Female     169     103      4
10     Male     195      81      2
11   Female     159      80      4
12   Female     192     101      3
13     Male     155      51      2
14     Male     191      79      2
15   Female     153     107      5
16   Female     157     110      5
17     Male     140     129      5
18     Male     144     145      5
19     Male     172     139      5
20     Male     157     110      5
21   Female     153     149      5
22   Female     169      97      4
23     Male     185     139      5
24   Female     172      67      2
25   Female     151      64      3
26     Male     190      95      3
27     Male     187      62      1
28   Female     163     159      5
29     Male     179     152      5
..      ...     ...     ...    ...
470    Male     147     142      5
471    Male     154     112      5
472  Female     178      65      2
473    Male     195     153      5
474  Female     167      79      3
475    Male     183     131      4
476  Female     164     142      5
477    Male     167      64      2
478  Female     151      55      2
479  Female     147     107      5
480  Female     155     115      5
481  Female     172     108      4
482  Female     142      86      5
483    Male     146      85      4
484  Female     188     115      4
485    Male     173     111      4
486  Female     160     109      5
487    Male     187      80      2
488    Male     198     136      4
489  Female     179     150      5
490  Female     164      59      2
491  Female     146     147      5
492  Female     198      50      0
493  Female     170      53      1
494    Male     152      98      5
495  Female     150     153      5
496  Female     184     121      4
497  Female     141     136      5
498    Male     150      95      5
499    Male     173     131      5

[500 rows x 4 columns]

In [24]:
databmi.Gender[databmi.Gender=="Male"]=1
databmi.Gender[databmi.Gender=="Female"]=0

C:\Users\Rahul\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.
C:\Users\Rahul\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

In [26]:
databmi

    Gender  Height  Weight  Index
0        1     174      96      4
1        1     189      87      2
2        0     185     110      4
3        0     195     104      3
4        1     149      61      3
5        1     189     104      3
6        1     147      92      5
7        1     154     111      5
8        1     174      90      3
9        0     169     103      4
10       1     195      81      2
11       0     159      80      4
12       0     192     101      3
13       1     155      51      2
14       1     191      79      2
15       0     153     107      5
16       0     157     110      5
17       1     140     129      5
18       1     144     145      5
19       1     172     139      5
20       1     157     110      5
21       0     153     149      5
22       0     169      97      4
23       1     185     139      5
24       0     172      67      2
25       0     151      64      3
26       1     190      95      3
27       1     187      62      1
28       0     163     159      5
29       1     179     152      5
..     ...     ...     ...    ...
470      1     147     142      5
471      1     154     112      5
472      0     178      65      2
473      1     195     153      5
474      0     167      79      3
475      1     183     131      4
476      0     164     142      5
477      1     167      64      2
478      0     151      55      2
479      0     147     107      5
480      0     155     115      5
481      0     172     108      4
482      0     142      86      5
483      1     146      85      4
484      0     188     115      4
485      1     173     111      4
486      0     160     109      5
487      1     187      80      2
488      1     198     136      4
489      0     179     150      5
490      0     164      59      2
491      0     146     147      5
492      0     198      50      0
493      0     170      53      1
494      1     152      98      5
495      0     150     153      5
496      0     184     121      4
497      0     141     136      5
498      1     150      95      5
499      1     173     131      5

[500 rows x 4 columns]

In [27]:
feature=databmi.iloc[:,0:3]

In [28]:
feature

    Gender  Height  Weight
0        1     174      96
1        1     189      87
2        0     185     110
3        0     195     104
4        1     149      61
5        1     189     104
6        1     147      92
7        1     154     111
8        1     174      90
9        0     169     103
10       1     195      81
11       0     159      80
12       0     192     101
13       1     155      51
14       1     191      79
15       0     153     107
16       0     157     110
17       1     140     129
18       1     144     145
19       1     172     139
20       1     157     110
21       0     153     149
22       0     169      97
23       1     185     139
24       0     172      67
25       0     151      64
26       1     190      95
27       1     187      62
28       0     163     159
29       1     179     152
..     ...     ...     ...
470      1     147     142
471      1     154     112
472      0     178      65
473      1     195     153
474      0     167      79
475      1     183     131
476      0     164     142
477      1     167      64
478      0     151      55
479      0     147     107
480      0     155     115
481      0     172     108
482      0     142      86
483      1     146      85
484      0     188     115
485      1     173     111
486      0     160     109
487      1     187      80
488      1     198     136
489      0     179     150
490      0     164      59
491      0     146     147
492      0     198      50
493      0     170      53
494      1     152      98
495      0     150     153
496      0     184     121
497      0     141     136
498      1     150      95
499      1     173     131

[500 rows x 3 columns]

In [29]:
target=databmi.iloc[:,3:4]

In [30]:
target

     Index
0        4
1        2
2        4
3        3
4        3
5        3
6        5
7        5
8        3
9        4
10       2
11       4
12       3
13       2
14       2
15       5
16       5
17       5
18       5
19       5
20       5
21       5
22       4
23       5
24       2
25       3
26       3
27       1
28       5
29       5
..     ...
470      5
471      5
472      2
473      5
474      3
475      4
476      5
477      2
478      2
479      5
480      5
481      4
482      5
483      4
484      4
485      4
486      5
487      2
488      4
489      5
490      2
491      5
492      0
493      1
494      5
495      5
496      4
497      5
498      5
499      5

[500 rows x 1 columns]

In [117]:
from sklearn.naive_bayes import GaussianNB,BernoulliNB,MultinomialNB

In [118]:
from sklearn.neighbors import KNeighborsClassifier

In [119]:
newfeature=feature.values.reshape(len(feature),3)

In [120]:
newtarget=target.values.reshape(len(target),1)

In [121]:
featuretrain=newfeature[:350]
featuretest=newfeature[350:]
targettrain=newtarget[:350]
targettest=newtarget[350:]

In [122]:
featuretest

array([[1, 184, 83],
       [1, 197, 88],
       [0, 160, 51],
       [1, 184, 153],
       [1, 190, 50],
       [1, 174, 90],
       [0, 189, 124],
       [0, 186, 143],
       [0, 180, 58],
       [0, 186, 148],
       [0, 193, 61],
       [1, 161, 103],
       [0, 151, 158],
       [0, 195, 147],
       [0, 184, 152],
       [1, 141, 80],
       [0, 185, 94],
       [0, 186, 127],
       [1, 142, 131],
       [0, 147, 67],
       [1, 151, 62],
       [0, 160, 124],
       [1, 185, 60],
       [0, 163, 63],
       [1, 174, 95],
       [0, 150, 144],
       [1, 142, 91],
       [1, 178, 142],
       [0, 154, 96],
       [1, 176, 87],
       [1, 159, 120],
       [1, 191, 62],
       [1, 177, 117],
       [1, 151, 154],
       [0, 182, 149],
       [0, 197, 72],
       [1, 146, 138],
       [0, 160, 83],
       [0, 157, 66],
       [0, 150, 50],
       [0, 167, 58],
       [0, 180, 70],
       [0, 183, 76],
       [0, 183, 87],
       [0, 152, 154],
       [0, 164, 71],
       [1, 187, 96],
       [1, 169, 136],
       [0, 149, 61],
       [1, 163, 137],
       [0, 195, 104],
       [1, 174, 107],
       [1, 182, 70],
       [1, 169, 110],
       [1, 193, 130],
       [1, 148, 141],
       [1, 186, 68],
       [1, 165, 143],
       [0, 146, 123],
       [0, 166, 133],
       [1, 179, 56],
       [0, 177, 101],
       [1, 181, 154],
       [0, 161, 154],
       [0, 157, 103],
       [0, 169, 98],
       [0, 152, 114],
       [0, 162, 64],
       [1, 162, 130],
       [0, 177, 61],
       [0, 195, 61],
       [1, 140, 146],
       [0, 186, 146],
       [0, 178, 107],
       [1, 174, 54],
       [0, 180, 59],
       [1, 188, 141],
       [0, 187, 130],
       [0, 153, 77],
       [0, 165, 95],
       [0, 178, 79],
       [0, 163, 154],
       [0, 150, 97],
       [1, 179, 127],
       [1, 165, 62],
       [1, 168, 158],
       [0, 153, 133],
       [1, 184, 157],
       [1, 188, 65],
       [0, 166, 153],
       [0, 172, 116],
       [1, 182, 73],
       [1, 143, 149],
       [1, 152, 146],
       [0, 186, 128],
       [1, 159, 140],
       [1, 146, 70],
       [0, 176, 121],
       [0, 146, 101],
       [1, 159, 145],
       [1, 162, 157],
       [0, 172, 90],
       [0, 169, 121],
       [1, 182, 50],
       [0, 183, 79],
       [1, 176, 77],
       [0, 188, 128],
       [0, 175, 83],
       [1, 154, 81],
       [0, 184, 147],
       [1, 179, 123],
       [1, 152, 132],
       [1, 179, 56],
       [0, 145, 141],
       [0, 181, 80],
       [1, 158, 127],
       [0, 188, 99],
       [1, 145, 142],
       [1, 161, 115],
       [1, 198, 109],
       [1, 147, 142],
       [1, 154, 112],
       [0, 178, 65],
       [1, 195, 153],
       [0, 167, 79],
       [1, 183, 131],
       [0, 164, 142],
       [1, 167, 64],
       [0, 151, 55],
       [0, 147, 107],
       [0, 155, 115],
       [0, 172, 108],
       [0, 142, 86],
       [1, 146, 85],
       [0, 188, 115],
       [1, 173, 111],
       [0, 160, 109],
       [1, 187, 80],
       [1, 198, 136],
       [0, 179, 150],
       [0, 164, 59],
       [0, 146, 147],
       [0, 198, 50],
       [0, 170, 53],
       [1, 152, 98],
       [0, 150, 153],
       [0, 184, 121],
       [0, 141, 136],
       [1, 150, 95],
       [1, 173, 131]], dtype=object)

In [123]:
teacherBer=BernoulliNB()
teacherMul=MultinomialNB()
teacherGa= GaussianNB()
teacherKnn=KNeighborsClassifier()

In [124]:
learnerBer=teacherBer.fit(featuretrain,targettrain)
learnerMul=teacherMul.fit(featuretrain,targettrain)
learnerGa=teacherGa.fit(featuretrain,targettrain)
learnerknn=teacher.fit(featuretrain,targettrain)

C:\Users\Rahul\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\utils\validation.py:578: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

In [125]:
Ya=targettest
YpBer=learnerBer.predict(featuretest)
YpMul=learnerMul.predict(featuretest)
YpGrass=learnerGa.predict(featuretest)

In [126]:
YpBer

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
       5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
       5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
       5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
       5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
       5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
       5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5], dtype=int64)

In [127]:
from sklearn.metrics import accuracy_score

In [128]:
accBer=accuracy_score(Ya,YpBer)*100
accMul=accuracy_score(Ya,YpMul)*100
accGa=accuracy_score(Ya,YpGrass)*100

In [129]:
accBer

42.0

In [130]:
accMul

72.66666666666667

In [131]:
accGa

70.66666666666667

In [132]:
table=pd.DataFrame({"accGa":[accGa],"accMul":[accMul],"accBer":[accBer]})

In [133]:
table

       accGa     accMul  accBer
0  70.666667  72.666667    42.0

In [134]:
learnerGa.predict([[1,173,70]])

array([2], dtype=int64)

In [135]:
learnerMul.predict([[1,173,70]])

array([2], dtype=int64)

In [136]:
learnerBer.predict([[1,173,70]])

array([5], dtype=int64)

In [137]:
learnerknn.predict([[1,173,70]])

array([2], dtype=int64)

In [138]:
learnerBer.predict([[1,177,69]])

array([5], dtype=int64)

In [139]:
learnerGa.predict([[1,177,69]])

array([2], dtype=int64)

In [140]:
learnerMul.predict([[1,177,69]])

array([2], dtype=int64)

In [141]:
learnerknn.predict([[1,177,69]])

array([2], dtype=int64)